Repository esbmc/esbmc, pull requests merged in 2024-01, with the labels that each got.

#1573 Work around macOS libc limitation for string-constant charset conversion
  src/util/string_constant.cpp
Labels: macOS

#1577 Automatic commits for clang-format changes
  src/esbmc/esbmc_parseoptions.cpp
Labels: CI

#1596 Fix range of rand() and random() to include upper endpoint
  regression/esbmc/github_1592-rand/gh-1592.c
  regression/esbmc/github_1592-rand/test.desc
  regression/esbmc/github_1592-random/gh-1592.c
  regression/esbmc/github_1592-random/test.desc
  src/c2goto/library/stdlib.c
Labels: OM
