Repository esbmc/esbmc, pull requests merged in 2025-09, with the labels that each got.

#2738 [python] Fix forward reference handling in function calls
  regression/python/forward-declaration/main.py
  regression/python/forward-declaration/test.desc
  regression/python/forward-declaration_fail/main.py
  regression/python/forward-declaration_fail/test.desc
  src/python-frontend/function_call_expr.cpp
  src/python-frontend/json_utils.h
Labels: python

#2744 [Concurrency] Don't terminate thread in pthread_exit
  regression/esbmc-cpp/unordered_map/basic_insert_fail/test.desc
  regression/esbmc-unix/03_use_if/test.desc
  regression/esbmc-unix/pthread_exit/main.c
  regression/esbmc-unix/pthread_exit/test.desc
  regression/esbmc-unix2/01_pthread64/test.desc
  src/c2goto/library/pthread_lib.c
Labels: concurrency

#2749 [python] Add AssertionError to ESBMC-Python exception operational model
  regression/python/AssertionError1/main.py
  regression/python/AssertionError1/test.desc
  regression/python/AssertionError1_fail/main.py
  regression/python/AssertionError1_fail/test.desc
  regression/python/AssertionError2/main.py
  regression/python/AssertionError2/test.desc
  regression/python/AssertionError2_fail/main.py
  regression/python/AssertionError2_fail/test.desc
  regression/python/insertion3/main.py
  regression/python/insertion3/test.desc
  regression/python/insertion3_fail/main.py
  regression/python/insertion3_fail/test.desc
  scripts/check_python_tests.sh
  src/python-frontend/models/exceptions.py
  src/python-frontend/type_utils.h
Labels: python

#2754 [python] enable strict type checking with mypy
  regression/python/missing-return14_fail/main.py
  regression/python/missing-return14_fail/test.desc
  scripts/check_python_tests.sh
  src/python-frontend/parser.py
Labels: python

#2776 [sv-comp] Overflow only works with incremental
  scripts/competitions/svcomp/esbmc-wrapper.py
Labels: SV-COMP

#2784 [simplifier] Add simplification rules for self-comparisons and idempotent expressions
  regression/esbmc/simplifier1/main.c
  regression/esbmc/simplifier1/test.desc
  regression/python/concat1_fail/test.desc
  regression/python/concat5_fail/test.desc
  regression/python/fstring2_fail/test.desc
  regression/python/fstring_fail/test.desc
  regression/python/string22_fail/test.desc
  regression/python/ternary_string_fail/test.desc
  src/util/simplify_expr2.cpp
Labels: symex

#2785 [simplifier] add arithmetic and bitwise expression simplifications
  regression/esbmc/simplifier2/main.c
  regression/esbmc/simplifier2/test.desc
  regression/esbmc/simplifier2_fail/main.c
  regression/esbmc/simplifier2_fail/test.desc
  regression/esbmc/simplifier3/main.c
  regression/esbmc/simplifier3/test.desc
  regression/esbmc/simplifier3_fail/main.c
  regression/esbmc/simplifier3_fail/test.desc
  regression/esbmc/simplifier4/main.c
  regression/esbmc/simplifier4/test.desc
  regression/esbmc/simplifier4_fail/main.c
  regression/esbmc/simplifier4_fail/test.desc
  src/util/simplify_expr2.cpp
Labels: symex

#2786 [simplifier] add associative simplification for logical AND/OR expressions
  regression/esbmc/simplifier5/main.c
  regression/esbmc/simplifier5/test.desc
  src/util/simplify_expr2.cpp
Labels: simplifier

#2790 [simplifier] add boolean, bitwise, and relational simplification rules with regression tests
  regression/esbmc/simplifier6/main.c
  regression/esbmc/simplifier6/test.desc
  regression/esbmc/simplifier6_fail/main.c
  regression/esbmc/simplifier6_fail/test.desc
  regression/goto-coverage/github_2071_1/test.desc
  regression/goto-coverage/github_2106_1/test.desc
  src/util/simplify_expr2.cpp
Labels: simplifier

#2791 [simplifier] Fix same_object simplification for typecast expressions
  regression/esbmc/same-object1/main.c
  regression/esbmc/same-object1/test.desc
  src/util/simplify_expr2.cpp
Labels: simplifier

#2794 clean up simplifier
  src/goto-programs/abstract-interpretation/ai_domain.cpp
  src/goto-programs/goto_check.cpp
  src/goto-symex/execution_state.cpp
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_catch.cpp
  src/goto-symex/symex_main.cpp
  src/pointer-analysis/goto_program_dereference.cpp
  src/pointer-analysis/value_set.cpp
  src/util/c_sizeof.cpp
Labels: simplifier

#2796 [simplifier] improve same_object2t::do_simplify()
  regression/esbmc/same-object2/main.c
  regression/esbmc/same-object2/test.desc
  src/util/simplify_expr2.cpp
Labels: simplifier

#2803 [simplifier] improve pointer offset simplification in VCC generation
  regression/esbmc/pointer-offset2/main.c
  regression/esbmc/pointer-offset2/test.desc
  src/util/simplify_expr2.cpp
Labels: simplifier
