Repository esbmc/esbmc, pull requests merged in 2025-07, with the labels that each got.

#2563 [smt] fix typecast handling for float-int conversions in integer encoding mode
  regression/esbmc/github_2560/main.c
  regression/esbmc/github_2560/test.desc
  regression/esbmc/github_2560_fail/main.c
  regression/esbmc/github_2560_fail/test.desc
  src/solvers/smt/smt_casts.cpp
Labels: smt

#2576 [smt] fix bitcast crash with integer/real encoding for int-to-float conversions
  regression/esbmc/github_2573/main.c
  regression/esbmc/github_2573/test.desc
  regression/esbmc/github_2573_1/main.c
  regression/esbmc/github_2573_1/test.desc
  src/solvers/smt/smt_bitcast.cpp
Labels: smt

#2577 [smt] fix signbit crash with integer/real encoding for floating-point values
  regression/esbmc/github_2572/main.c
  regression/esbmc/github_2572/test.desc
  regression/esbmc/github_2572_1/main.c
  regression/esbmc/github_2572_1/test.desc
  regression/esbmc/github_2572_2/main.c
  regression/esbmc/github_2572_2/test.desc
  src/solvers/smt/smt_conv.cpp
Labels: smt

#2581 [smt] fix crash in convert_bitcast when converting float to bv in int_encoding mode
  regression/esbmc/github_2579/main.c
  regression/esbmc/github_2579/test.desc
  regression/esbmc/github_2579_1/main.c
  regression/esbmc/github_2579_1/test.desc
  src/solvers/smt/smt_bitcast.cpp
Labels: smt

#2583 [Concurrency] Rename expr as level1 in globals_list
  regression/esbmc-unix/01_cond_01/test.desc
  regression/esbmc-unix2/00_mpor2/main.c
  regression/esbmc-unix2/00_mpor2/test.desc
  src/goto-symex/execution_state.cpp
Labels: concurrency

#2594 [smt] integrate bitwzula v.0.8.1
  BUILDING.md
  src/solvers/bitwuzla/CMakeLists.txt
Labels: smt

#2631 [sv-comp] fixed wrapper for termination
  scripts/competitions/svcomp/esbmc-wrapper.py
Labels: SV-COMP

#2633 [cpp] add missing priority_queue constructor and comparator support
  regression/esbmc-cpp/priority_queue/priority_queue_constructor-2/test.desc
  regression/esbmc-cpp/priority_queue/priority_queue_constructor_bug-2/test.desc
  regression/esbmc-cpp/template/priority_queue_constructor-2/test.desc
  regression/esbmc-cpp/template/priority_queue_constructor_bug-2/test.desc
  src/cpp/library/queue
Labels: C++

#2636 [c++] fix set implementation compilation errors
  regression/esbmc-cpp/multiset/multiset-clear-bug/test.desc
  regression/esbmc-cpp/multiset/multiset-clear/test.desc
  regression/esbmc-cpp/multiset/multiset-lower_bound/test.desc
  regression/esbmc-cpp/multiset/multiset-operator-assign-bug/test.desc
  regression/esbmc-cpp/multiset/multiset-operator-assign/test.desc
  regression/esbmc-cpp/multiset/multiset-upper_bound/test.desc
  regression/esbmc-cpp/set/set-clear/test.desc
  regression/esbmc-cpp/set/set-operator-assign-bug/test.desc
  regression/esbmc-cpp/set/set-operator-assign/test.desc
  src/cpp/library/set
Labels: C++

#2637 [c++] add template sort(Compare) overload to list implementation
  regression/esbmc-cpp/list/list_sort-2/test.desc
  regression/esbmc-cpp/list/list_sort_bug-2/test.desc
  regression/esbmc-cpp/template/list_sort/test.desc
  regression/esbmc-cpp/template/list_sort_bug/test.desc
  src/cpp/library/list
Labels: C++

#2645 [c++] fix iterator memory safety issues in string model
  regression/esbmc-cpp/string/string_erase_2/test.desc
  regression/esbmc-cpp/string/string_erase_final/test.desc
  regression/esbmc-cpp/string/string_insert_6/test.desc
  regression/esbmc-cpp/string/string_insert_7/test.desc
  regression/esbmc-cpp/string/string_insert_final/test.desc
  regression/esbmc-cpp/string/string_replace_7/test.desc
  regression/esbmc-cpp/string/string_replace_8/test.desc
  regression/esbmc-cpp/string/string_replace_9/test.desc
  src/cpp/library/string
Labels: C++

#2644 [python] Extend chr() function to process multibyte characters
  regression/python/casting-chr-func/main.py
  regression/python/casting-chr-func/test.desc
  regression/python/casting-chr-multibyte-fail/main.py
  regression/python/casting-chr-multibyte-fail/test.desc
  regression/python/casting-chr-multibyte-reassign/main.py
  regression/python/casting-chr-multibyte-reassign/test.desc
  regression/python/casting-chr-multibyte/main.py
  regression/python/casting-chr-multibyte/test.desc
  regression/python/casting-chr-multibyte2/main.py
  regression/python/casting-chr-multibyte2/test.desc
  regression/python/casting-chr-var-multibyte/main.py
  regression/python/casting-chr-var-multibyte/test.desc
  regression/python/casting15-fail/test.desc
  regression/python/casting16/main.py
  src/python-frontend/function_call_expr.cpp
  src/python-frontend/function_call_expr.h
Labels: python

#2648 [c++] fix stack constructor to properly initialize from container
  regression/esbmc-cpp/stack/stack_constructor/test.desc
  regression/esbmc-cpp/stack/stack_constructor_bug/test.desc
  src/cpp/library/stack
Labels: C++

#2649 [c++] fix iterator invalidation in set range erase
  regression/esbmc-cpp/cpp/ch21_6/test.desc
  regression/esbmc-cpp/multiset/multiset-erase-bug/test.desc
  regression/esbmc-cpp/multiset/multiset-erase/test.desc
  regression/esbmc-cpp/multiset/multiset-find-bug/test.desc
  regression/esbmc-cpp/multiset/multiset-find/test.desc
  regression/esbmc-cpp/set/set-erase-bug/test.desc
  regression/esbmc-cpp/set/set-erase/test.desc
  regression/esbmc-cpp/set/set-find-bug/test.desc
  regression/esbmc-cpp/set/set-find/test.desc
  regression/esbmc-cpp/set/set-loop-with-inserts-1-bug/test.desc
  regression/esbmc-cpp/set/set-with-objects/test.desc
  src/cpp/library/set
Labels: C++
