Repository esbmc/esbmc, pull requests merged in 2025-04, with the labels that each got.

#2385 [Concurrency] unified data race flag
  regression/esbmc-unix/github_2384/main.c
  regression/esbmc-unix/github_2384/test.desc
  src/goto-programs/add_race_assertions.cpp
Labels: needs-svcomp-run

#2399 [data-races-check] get rid of static analysis
  src/esbmc/esbmc_parseoptions.cpp
  src/goto-programs/add_race_assertions.cpp
  src/goto-programs/add_race_assertions.h
  src/goto-programs/rw_set.h
Labels: has-svcomp-results

#2414 [python-frontend] Handling list slicing
  .gitignore
  regression/python/slicing-bounds-fail/main.py
  regression/python/slicing-bounds-fail/test.desc
  regression/python/slicing-fail/main.py
  regression/python/slicing-fail/test.desc
  regression/python/slicing/main.py
  regression/python/slicing/test.desc
  src/python-frontend/python_converter.cpp
Labels: python
